<?php
/**
 * DishApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SwaggerServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Gastronoslim
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0_inProgress
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Tests\Functional;

/**
 * DishApiTest Class Doc Comment
 *
 * @category Class
 * @package  SwaggerServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DishApiTest extends BaseTestCase
{

    public function testgetdish()
    {
        $response = $this->runApp('get', '/plats/1');
        $this->assertEquals(200, $response->getStatusCode());

    }

    public function testgetdishBadArgs()
    {
        $response = $this->runApp('get', '/plats/987987956414894');
        $this->assertEquals(404, $response->getStatusCode());

    }

    public function testgetdishNoArgs()
    {
        $response = $this->runApp('get', '/plats/');
        $this->assertEquals(400, $response->getStatusCode());

    }
}
