<?php
/**
 * RestaurantApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SwaggerServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Gastronoslim
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0_inProgress
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Tests\Functional;

/**
 * RestaurantApiTest Class Doc Comment
 *
 * @category Class
 * @package  SwaggerServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RestaurantApiTest extends BaseTestCase
{
      
    /**
     * Test case for restaurantFind
     *
     * listing des restaurant par ville.
     *
     */

    public function testrestaurantFindByVile()
    {
        $response = $this->runApp('GET', '/restaurant?city=Longnes', null, 'ABCDEF0123456789');
        $this->assertEquals(200, $response->getStatusCode());
    }


    // Test with no authent token
    public function testrestaurantFindNoLogin()
    {
        $response = $this->runApp('GET', '/restaurant');
        $this->assertEquals(401, $response->getStatusCode());
    }


    // Test restaurantFind with no parameter
    public function testrestaurantFindNoParams()
    {
        $response = $this->runApp('GET', '/restaurant', null, 'ABCDEF0123456789');
        $this->assertEquals(400, $response->getStatusCode());
    }

    // Test restaurantFind with bad parameter
    public function testrestaurantFindBadParam()
    {
        $response = $this->runApp('GET', '/restaurant?valle=34395533200022', null, 'ABCDEF0123456789');
        $this->assertEquals(400, $response->getStatusCode());
    }
}
