<?php
/**
 * RestaurantApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SwaggerServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Gastronoslim
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0_inProgress
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Tests\Functional;

/**
 * RestaurantApiTest Class Doc Comment
 *
 * @category Class
 * @package  SwaggerServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RestaurantApiTest extends BaseTestCase
{
      
    /**
     * Test case for restaurantFind
     *
     * listing des restaurant par ville.
     *
     */

    public function testrestaurantFindByVile()
    {
        $response = $this->runApp('GET', '/restaurant?city=78180');
        $this->assertContains('token', (string)$response->getBody());
        $this->assertEquals(200, $response->getStatusCode());
    }
   public function testrestaurantFindByVileAndBudget()
    {
        $response = $this->runApp('GET', '/restaurant?city=Longnes&idBudget=2');
        $this->assertEquals(200, $response->getStatusCode());
    }
    // Test restaurantFind with no parameter
    public function testrestaurantFindNoParams()
    {
        $response = $this->runApp('GET', '/restaurant', null);
        $this->assertEquals(400, $response->getStatusCode());
    }
    public function testrestaurantFindNotFound()
    {
        $response = $this->runApp('GET', '/restaurant?city=Humm', null);
        $this->assertEquals(404, $response->getStatusCode());
    }
    // Test restaurantFind with bad parameter
    public function testrestaurantFindBadParam()
    {
        $response = $this->runApp('GET', '/restaurant?valle=34395533200022', null);
        $this->assertEquals(400, $response->getStatusCode());
    }
    public function testrestaurantGet()
    {
        $response = $this->runApp('GET', '/restaurant/1', null);
        $this->assertEquals(200, $response->getStatusCode());
    }
    public function testrestaurantGetBadArgs()
    {
        $response = $this->runApp('GET', '/restaurant/5', null);

        $this->assertEquals(404, $response->getStatusCode());
    }
    public function testrestaurantGetNoArgs()
    {
        $response = $this->runApp('GET', '/restaurant/', null);

        $this->assertEquals(400, $response->getStatusCode());
    }
    public function testrestaurantUp()
    {
        $response = $this->runApp('GET', '/restaurant/positif/1',null);
        $this->assertEquals(200, $response->getStatusCode());
    }
    public function testrestaurantUpBadArgs()
    {
        $response = $this->runApp('GET', '/restaurant/positif/2', null);

        $this->assertEquals(404, $response->getStatusCode());
    }
    public function testrestaurantUpNoArgs()
    {
        $response = $this->runApp('GET', '/restaurant/positif/', null);
        $this->assertEquals(400, $response->getStatusCode());
    }
    public function testrestaurantDown()
    {
        $response = $this->runApp('GET', '/restaurant/negatif/1',null);
        $this->assertEquals(200, $response->getStatusCode());
    }
    public function testrestaurantDownBadArgs()
    {
        $response = $this->runApp('GET', '/restaurant/negatif/2', null);

        $this->assertEquals(404, $response->getStatusCode());
    }
    public function testrestaurantDownNoArgs()
    {
        $response = $this->runApp('GET', '/restaurant/negatif/', null);
        $this->assertEquals(400, $response->getStatusCode());
    }

}
